// Code generated by scripts/frame-delegates.py; DO NOT EDIT.
package drissionpage

import (
	"context"
	"encoding/json"
	"github.com/go-rod/rod/lib/proto"
	"time"
)

func (f *ChromiumFrame) ActiveElement(ctx context.Context) (*ChromiumElement, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.ActiveElement(ctx)
}
func (f *ChromiumFrame) NewElement(ctx context.Context, markup string) (*ChromiumElement, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.NewElement(ctx, markup)
}
func (f *ChromiumFrame) RunExpression(ctx context.Context, expression string) (json.RawMessage, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.RunExpression(ctx, expression)
}
func (f *ChromiumFrame) ReadyState(ctx context.Context) (string, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return "", err
	}
	return t.ReadyState(ctx)
}
func (f *ChromiumFrame) UserAgent(ctx context.Context) (string, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return "", err
	}
	return t.UserAgent(ctx)
}
func (f *ChromiumFrame) JSON(ctx context.Context, out any) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.JSON(ctx, out)
}
func (f *ChromiumFrame) SaveMHTML(ctx context.Context, path string) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.SaveMHTML(ctx, path)
}
func (f *ChromiumFrame) GetBlob(ctx context.Context, target string) ([]byte, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.GetBlob(ctx, target)
}
func (f *ChromiumFrame) ToSession(ctx context.Context, navigate bool) (*SessionPage, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.ToSession(ctx, navigate)
}
func (f *ChromiumFrame) CookiesToSession(ctx context.Context, s *SessionPage) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.CookiesToSession(ctx, s)
}
func (f *ChromiumFrame) CookiesFromSession(ctx context.Context, s *SessionPage, target string) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.CookiesFromSession(ctx, s, target)
}
func (f *ChromiumFrame) ScrollToTop(ctx context.Context) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.ScrollToTop(ctx)
}
func (f *ChromiumFrame) ScrollToHalf(ctx context.Context) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.ScrollToHalf(ctx)
}
func (f *ChromiumFrame) ScrollToRightmost(ctx context.Context) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.ScrollToRightmost(ctx)
}
func (f *ChromiumFrame) ScrollToLeftmost(ctx context.Context) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.ScrollToLeftmost(ctx)
}
func (f *ChromiumFrame) SetSmoothScroll(ctx context.Context, on bool) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.SetSmoothScroll(ctx, on)
}
func (f *ChromiumFrame) RunJSLoaded(ctx context.Context, script string, args ...any) (json.RawMessage, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.RunJSLoaded(ctx, script, args...)
}
func (f *ChromiumFrame) RunCDPLoaded(ctx context.Context, method string, params any) (json.RawMessage, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.RunCDPLoaded(ctx, method, params)
}
func (f *ChromiumFrame) SEles(ctx context.Context, locator any) ([]*SessionElement, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.SEles(ctx, locator)
}
func (f *ChromiumFrame) StartDisplayRecording(ctx context.Context) (*DisplayRecording, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.StartDisplayRecording(ctx)
}
func (f *ChromiumFrame) Window(ctx context.Context) (*proto.BrowserGetWindowForTargetResult, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.Window(ctx)
}
func (f *ChromiumFrame) Hybrid(ctx context.Context) (*HybridPage, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.Hybrid(ctx)
}
func (f *ChromiumFrame) EvalHandle(ctx context.Context, script string, args ...any) (*JSHandle, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.EvalHandle(ctx, script, args...)
}
func (f *ChromiumFrame) Listen(ctx context.Context, filter ListenFilter) (*Listener, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.Listen(ctx, filter)
}
func (f *ChromiumFrame) Console(ctx context.Context) (*Console, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.Console(ctx)
}
func (f *ChromiumFrame) NativeWindows(ctx context.Context) ([]NativeWindow, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.NativeWindows(ctx)
}
func (f *ChromiumFrame) HideWindow(ctx context.Context) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.HideWindow(ctx)
}
func (f *ChromiumFrame) ShowWindow(ctx context.Context) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.ShowWindow(ctx)
}
func (f *ChromiumFrame) WatchState(ctx context.Context) (*PageStateObserver, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.WatchState(ctx)
}
func (f *ChromiumFrame) ShowTrail(ctx context.Context, on bool) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.ShowTrail(ctx, on)
}
func (f *ChromiumFrame) XPathValues(ctx context.Context, expression string) (json.RawMessage, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.XPathValues(ctx, expression)
}
func (f *ChromiumFrame) StartScreencast(ctx context.Context, directory string) (*Screencast, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.StartScreencast(ctx, directory)
}
func (f *ChromiumFrame) StartPeriodicScreencast(ctx context.Context, directory string, interval time.Duration) (*Screencast, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.StartPeriodicScreencast(ctx, directory, interval)
}
func (f *ChromiumFrame) StartRecording(ctx context.Context, directory, mode string) (*Screencast, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.StartRecording(ctx, directory, mode)
}
func (f *ChromiumFrame) AutoHandleAlerts(ctx context.Context, accept bool, prompt string) (func(), error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.AutoHandleAlerts(ctx, accept, prompt)
}
func (f *ChromiumFrame) ElementAt(ctx context.Context, x, y float64) (*ChromiumElement, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.ElementAt(ctx, x, y)
}
func (f *ChromiumFrame) PDF(ctx context.Context, path string, options ...proto.PagePrintToPDF) ([]byte, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.PDF(ctx, path, options...)
}
func (f *ChromiumFrame) Save(ctx context.Context, path string) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.Save(ctx, path)
}
func (f *ChromiumFrame) Activate(ctx context.Context) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.Activate(ctx)
}
func (f *ChromiumFrame) Back(ctx context.Context) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.Back(ctx)
}
func (f *ChromiumFrame) Forward(ctx context.Context) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.Forward(ctx)
}
func (f *ChromiumFrame) StopLoading(ctx context.Context) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.StopLoading(ctx)
}
func (f *ChromiumFrame) Cookies(ctx context.Context) ([]*proto.NetworkCookie, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.Cookies(ctx)
}
func (f *ChromiumFrame) SetCookies(ctx context.Context, cookies []*proto.NetworkCookieParam) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.SetCookies(ctx, cookies)
}
func (f *ChromiumFrame) SetViewport(ctx context.Context, width, height int) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.SetViewport(ctx, width, height)
}
func (f *ChromiumFrame) SetHeaders(ctx context.Context, headers map[string]string) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.SetHeaders(ctx, headers)
}
func (f *ChromiumFrame) Storage(ctx context.Context, session bool) (map[string]string, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return nil, err
	}
	return t.Storage(ctx, session)
}
func (f *ChromiumFrame) SetStorage(ctx context.Context, session bool, key string, value *string) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.SetStorage(ctx, session, key, value)
}
func (f *ChromiumFrame) ClearStorage(ctx context.Context, session bool) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.ClearStorage(ctx, session)
}
func (f *ChromiumFrame) SetUserAgent(ctx context.Context, ua, platform string) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.SetUserAgent(ctx, ua, platform)
}
func (f *ChromiumFrame) SetBlockedURLs(ctx context.Context, urls ...string) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.SetBlockedURLs(ctx, urls...)
}
func (f *ChromiumFrame) SetWindow(ctx context.Context, bounds *proto.BrowserBounds) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.SetWindow(ctx, bounds)
}
func (f *ChromiumFrame) DeleteCookie(ctx context.Context, name, target, domain, path string) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.DeleteCookie(ctx, name, target, domain, path)
}
func (f *ChromiumFrame) ClearCookies(ctx context.Context) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.ClearCookies(ctx)
}
func (f *ChromiumFrame) WaitURL(ctx context.Context, text string, exclude bool) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.WaitURL(ctx, text, exclude)
}
func (f *ChromiumFrame) WaitTitle(ctx context.Context, text string, exclude bool) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.WaitTitle(ctx, text, exclude)
}
func (f *ChromiumFrame) WaitDeleted(ctx context.Context, locator any) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.WaitDeleted(ctx, locator)
}
func (f *ChromiumFrame) HandleAlert(ctx context.Context, accept bool, prompt string) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.HandleAlert(ctx, accept, prompt)
}
func (f *ChromiumFrame) InitJS(ctx context.Context, script string) (string, error) {
	t, err := f.Resolve(ctx)
	if err != nil {
		return "", err
	}
	return t.InitJS(ctx, script)
}
func (f *ChromiumFrame) RemoveInitJS(ctx context.Context, id string) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.RemoveInitJS(ctx, id)
}
func (f *ChromiumFrame) WaitElements(ctx context.Context, locators []any, anyOne bool) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.WaitElements(ctx, locators, anyOne)
}
func (f *ChromiumFrame) WaitDisplayed(ctx context.Context, locator any, displayed bool) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.WaitDisplayed(ctx, locator, displayed)
}
func (f *ChromiumFrame) WaitURLChange(ctx context.Context, text string, exclude bool) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.WaitURLChange(ctx, text, exclude)
}
func (f *ChromiumFrame) WaitTitleChange(ctx context.Context, text string, exclude bool) error {
	t, err := f.Resolve(ctx)
	if err != nil {
		return err
	}
	return t.WaitTitleChange(ctx, text, exclude)
}
