"""Generate context/error delegates so frame sessions are rebound per call."""
from pathlib import Path
import re

root = Path(__file__).resolve().parent.parent
files = [p for p in root.glob('*.go') if not p.name.endswith('_test.go') and p.name != 'frame_delegates.go']
existing = set(re.findall(r'func \(\w+ \*ChromiumFrame\) (\w+)\(', '\n'.join(p.read_text(encoding='utf-8') for p in files)))
output = ['// Code generated by scripts/frame-delegates.py; DO NOT EDIT.', 'package drissionpage', 'import ("context";"encoding/json";"time";"github.com/go-rod/rod/lib/proto")']
for path in files:
    for name, args, returns in re.findall(r'^func \(t \*ChromiumTab\) (\w+)\((.*?)\) (.*?) \{', path.read_text(encoding='utf-8'), re.M):
        if name in existing or not name[0].isupper() or not args.startswith('ctx context.Context'):
            continue
        types = returns.strip('()').split(', ')
        if types[-1] != 'error':
            continue
        params = [arg.split()[0] + ('...' if '...' in arg else '') for arg in args.split(', ')]
        zero = ['nil' if typ.startswith(('*', '[]', 'map[', 'func(')) or typ == 'json.RawMessage' else ('""' if typ == 'string' else ('0' if typ in ('int', 'float64') else 'false')) for typ in types[:-1]]
        failure = ', '.join(zero + ['err'])
        output.append('func (f *ChromiumFrame) ' + name + '(' + args + ') ' + returns + ' { t,err:=f.Resolve(ctx);if err!=nil{return ' + failure + '};return t.' + name + '(' + ', '.join(params) + ') }')
(root / 'frame_delegates.go').write_text('\n'.join(output) + '\n', encoding='utf-8')
